select * from [user]
select * from account
select * from loan
select * from [admin]
select * from loan_payment
select * from rejected_user
select * from [transaction]
select * from archived_account
select * from archived_transaction
select * from archived_user